# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeezeIt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeezeIt

pod 'SwiftKeychainWrapper'
  target 'LeezeItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeezeItUITests' do
    # Pods for testing
  end

end
